<?php
return array(
    'call' => 'ligar',
    'calls' => 'Chamadas',
    'on_call' => 'Em Chamada',
    'attended_calls' => 'Ligações atendidas',
    'props' => array(
        'title' => 'Título',
        'description' => 'Descrição',
        'start_date_time' => 'Hora de início',
        'estimated_period' => 'Período Estimado',
        'type' => 'Tipo',
        'status' => 'Status',
        'period' => 'Período',
        'body' => 'Corpo',
    ),
    'is_cancelled' => 'A chamada foi cancelada.',
    'is_not_live' => 'A chamada não está ao vivo.',
    'start_call' => 'Iniciar chamada',
    'you' => 'Você',
    'screen' => 'Tela',
    'your_screen' => 'Sua tela',
    'toggle_audio' => 'Alternar áudio',
    'mute_audio' => 'Áudio mudo',
    'unmute_audio' => 'Ativar áudio',
    'toggle_video' => 'Alternar Video',
    'mute_video' => 'Vídeo Mudo',
    'unmute_video' => 'Vídeo com áudio',
    'invalid_action_with_status' => 'Chamada está :attribute, esta não é uma ação válida.',
    'call_details' => 'Detalhes da chamada',
    'member_online' => 'membro está online!',
    'members_online' => 'membros estão online!',
    'join' => 'Join',
    'invitee_joined' => 'Você entrou na chamada.',
    'invitee_left' => 'Você deixou a ligação.',
    'invitee_ended' => 'Você encerrou a ligação.',
    'left' => 'Esquerda',
    'cancel' => 'Cancelar',
    'cancel_call' => 'Cancelar chamada',
    'join_call' => 'Entrar na chamada',
    'end_call' => 'Terminar chamada',
    'leave_call' => 'Deixar ligação',
    'join_a_call' => 'Participar de uma chamada',
    'share_screen' => 'Compartilhar tela',
    'duplicate_tab' => 'Você já tem uma guia aberta para uma página de chamada ao vivo!',
    'stop_sharing_screen' => 'Parar de compartilhar a tela',
);
