<?php return array (
  'general' => 'Geral',
  'assets' =>
  array (
    'assets' => 'Ativos',
    'image' => 'Imagem',
    'logo' => 'Logo',
    'light' => 'Logo (Light)',
    'logo_light' => 'Logo (Light)',
    'icon' => 'Ícone',
    'favicon' => 'Favicon',
    'nothing_uploaded' => 'Sem :attribute uploaded.',
  ),
  'auth' =>
  array (
    'auth' => 'Autenticação',
    'registration' => 'Cadastro',
    'email_verification' => 'Email precisa de verificação',
    'account_approval' => 'A conta precisa de aprovação',
    'client_id' => 'ID do Cliente',
    'client_secret' => 'Client Secret',
    'session_lifetime' => 'Tempo da sessão',
    'reset_password' => 'Redefinir senha',
    'reset_password_token_lifetime' => 'Redefinir a senha do token',
    'lock_screen' => 'Tela de bloqueio',
    'social_login' => 'Social Login',
    'login_with' => 'Logar com',
    'sms_otp_login' => 'Login com senha temporária via SMS',
    'email_otp_login' => 'Login com senha temporária via Email',
    'google' => 'Google',
    'facebook' => 'Facebook',
    'twitter' => 'Twitter',
    'github' => 'GitHub',
    'lock_screen_timeout' => 'Tempo limite da tela de bloqueio',
    'login_throttle' => 'Login Throttle',
    'login_throttle_attempt' => 'Tentativa de Login Throttle',
    'login_throttle_timeout' => 'Tempo limite do Login Throttle',
    'two_factor_security' => 'Identificação por dois fatores',
    'parent_otp_login' => 'Login com senha temporária para pais',
  ),
  'pusher' =>
  array(
    'credential' => 'Pusher Credential',
    'credential_required' => 'Pusher Credential is required and has not been set!',
    'app_id' => 'Pusher App ID',
    'app_key' => 'Pusher App Key',
    'app_secret' => 'Pusher App Secret',
    'app_cluster' => 'Pusher App Cluster'
  ),
  'signal' =>
  array(
    'signaling_server' => 'Servidor de Sinalização',
    'url' => 'URL do servidor de sinalização'
  ),
  'basic' =>
  array (
    'basic' => 'Básico',
    'contact_information' => 'Informações de Contato',
    'org_information' => 'Informação da Organização',
    'org_tax_number' => 'Número de identificação fiscal',
    'org_foundation_date' => 'Dia da fundação',
    'org_name' => 'Nome',
    'org_recognition_body' => 'Corpo de Reconhecimento',
    'reg_no' => 'Reg. No.',
    'org_recognition_number' => 'Número de Reconhecimento',
    'org_running_body' => 'Running Body',
    'org_city' => 'Cidade',
    'org_address_line1' => 'Linha de Endereço 1',
    'org_address_line2' => 'Linha de Endereço 2',
    'org_country' => 'País',
    'org_state' => 'Estado',
    'org_website' => 'Website',
    'org_zipcode' => 'Código PIN',
    'org_phone' => 'Telefone',
    'org_email' => 'Email',
    'org_fax' => 'Fax',
  ),
  'config' => 'Config',
  'configuration' => 'Configuração',
  'locale' =>
  array (
    'locale' => 'Local',
    'locales' => 'Locais',
    'cannot_change_locale' => 'Não é possível alterar o local depois de criado.',
    'module' => 'Módulo',
    'key' => 'Key',
    'props' =>
    array (
      'name' => 'Nome',
      'word' => 'palavra',
      'is_default' => 'É padrão?',
    ),
    'module_description' => 'Traduza seu aplicativo para qualquer local, adicione uma nova palavra para tradução, atualize a tradução e mude para seu próprio local',
    'translation' => 'Tradução',
    'module_title' => 'Adicione alguns locais aqui!',
  ),
  'mail' =>
  array (
    'mail' => 'Mail',
    'driver' => 'Driver',
    'from_address' => 'A partir do endereço',
    'from_name' => 'A partir do nome',
    'mailgun_domain' => 'Domínio',
    'mailgun_endpoint' => 'Endpoint',
    'mailgun_encryption' => 'Encryption',
    'mailgun_host' => 'Hospedeiro',
    'mailgun_password' => 'Senha',
    'mailgun_port' => 'Port',
    'mailgun_secret' => 'Secret',
    'mailgun_username' => 'Nome de Usuário',
    'smtp_encryption' => 'Encryption',
    'smtp_host' => 'Host',
    'smtp_password' => 'Senha',
    'smtp_port' => 'Port',
    'smtp_username' => 'Nome de Usuário',
    'mandrill_secret' => 'Secret',
  ),
  'module' =>
  array (
    'module' => 'Module',
  ),
  'notification' =>
  array (
    'notification' => 'Notificação',
    'notifications' => 'Notificações',
    'setting' => 'Configuração de Notificação',
  ),
  'ice_server' =>
  array (
    'server' => 'Servidor',
    'ice_server' => 'Servidor ICE',
    'ice_servers' => 'Servers ICE ',
    'urls' => 'URLs',
    'requires_credential' => 'Requer credencial',
    'expirable_credential' => 'Credencial Expirável',
    'username' => 'Nome de Usuário',
    'credential' => 'Credencial',
    'secret' => 'Secret',
    'expires_in' => 'Expira em (in Seconds)',
    'time_difference' => 'Diferença de tempo (in Minutes)',
  ),
  'payment_gateway' =>
  array (
    'payment_gateway' => 'Gateway de pagamento',
    'live_mode' => ':attribute Live Mode',
    'key' => ':attribute Public Key / API Key',
    'secret' => ':attribute Secret Key / API Secret',
    'charge_handling_fee' => 'Taxa de manuseio de cobrança',
    'fixed_handling_fee' => 'Taxa fixa de manuseio',
    'attr_handling_fee' => ':taxa de manuseio de atributo',
    'handling_fee' => 'Taxa de manuseio',
    'disabled' => 'Gateway de pagamento desativado!',
  ),
  'permission' =>
  array (
    'permission' => 'Permissão',
    'permissions' => 'Permissões',
    'denied' => 'Você não tem permissão para realizar esta ação.',
    'assign_permission_module' => 'Atribuir permissão (:attribute)',
    'props' =>
    array (
      'name' => 'Name',
    ),
    'module_title' => 'Listando todas as permissões',
    'module_description' => 'Controle quem pode fazer o quê, adicione várias funções e atribua permissões a essas funções.',
  ),
  'role' =>
  array (
    'role' => 'Função',
    'roles' => 'Funções',
    'props' =>
    array (
      'name' => 'Nome',
      'is_default' => 'É padrão',
    ),
    'module_title' => 'Listando todas as funções',
    'module_description' => 'Crie várias funções para seus usuários, atribua permissões diferentes com base nas funções.',
  ),
  'scheduled_job' => 'Trabalho Programado',
  'setup_wizard' =>
  array (
    'hide_setup_wizard' => 'Ocultar assistente de configuração',
    'finish_button_content' => 'Pronto!',
    'next_button_content' => 'Próximo',
    'previous_button_content' => 'Anterior',
    'subtitle' => 'Configurar InstiKit',
    'name' => 'Assistente de configuração fácil',
  ),
  'sms' =>
  array (
    'sms' => 'SMS',
    'gateway' => 'SMS Gateway',
    'custom_api_get_url' => 'API Get URL',
    'custom_api_number_prefix' => 'API Number Prefix',
    'custom_api_sender_id_param' => 'API Sender Id Parameter',
    'custom_api_sender_id' => 'API Sender Id/Number',
    'custom_api_receiver_param' => 'API Receiver Parameter',
    'custom_api_message_param' => 'API Message Parameter',
    'custom_api_accepts_multiple_receiver' => 'API accepts multiple receiver?',
    'max_per_chunk' => 'Max SMS in single queue',
  ),
  'social' =>
  array (
    'network' => 'Rede Social',
    'url' => ':attribute Link',
  ),
  'system' =>
  array (
    'system' => 'Sistema',
    'enable_backup' => 'Habilitar Backup',
    'locale' => 'Local',
    'date_format' => 'Formato de data',
    'time_format' => 'Formato de hora',
    'fy_start' => 'Início do ano fiscal',
    'timezone' => 'Fuso horário',
    'currency' => 'Moeda',
    'page_length' => 'Comprimento da página',
    'per_page' => ':attribute per page',
    'direction' => 'Direção',
    'direction_options' =>
    array (
      'ltr' => 'Esquerda para a direita',
      'rtl' => 'Direita para esquerda',
    ),
    'print' =>
    array (
      'settings' => 'Configurações de impressão',
      'show_header' => 'Mostrar Cabeçalho',
      'header_margin' => 'Margem do Cabeçalho',
      'footer_margin' => 'Margem do rodapé',
    ),
    'enable_print_preview' => 'Enable Print Preview',
    'show_error_display' => 'Mostrar tela de erro',
    'footer_credit' => 'Footer Credit',
    'enable_https' => 'Crédito de rodapé',
    'enable_ip_filter' => 'Ativar filtro de IP',
    'enable_maintenance_mode' => 'Habilitar modo de manutenção',
    'maintenance_mode_message' => 'Mensagem do modo de manutenção',
    'mode' => 'Modo',
    'test_mode' => 'Modo Demo',
    'enable_multilingual' => 'Habilitar multilíngue',
    'enable_todo' => 'Habilitar o que fazer',
    'under_maintenance' => 'Em manutenção',
  ),
  'ui' =>
  array (
    'scheme' => 'Esquema',
    'color_scheme' => 'Esquema de cores',
    'navigation' => 'Navegação',
    'navigation_menu' => 'menu de navegação',
    'icon_alignment' => 'Alinhamento de ícone',
    'letter_icon' => 'Ícone de Carta',
    'navbar' => 'Barra de Navegação',
    'top_navbar' => 'Barra de navegação do topo',
    'fixed_on_top' => 'Barra de navegação fixa',
    'color' => 'Cor',
    'wallpaper' => 'Wallpaper',
    'light_logo' => 'Light Logo',
    'hide_navbar' => 'Esconder barra de navegação',
    'height' => 'Altura',
    'normal' => 'Normal',
    'full' => 'Cheio',
    'toggle_sidebar' => 'Alternar barra lateral',
    'toggle_fullscreen' => 'Alternar para o modo tela cheia',
    'style' => 'Estilo',
    'show' => 'Mpstrar',
    'shadow' => 'Sombra',
    'sidebar' => 'Barra Lateral',
    'backdrop' => 'Pano de fundo',
    'background' => 'Background',
    'bg_color' => 'Cor do Background',
    'page_bg_color' => 'Cor de fundo da página',
    'page_container_bg_color' => 'Container Background Color',
    'page_and_container' => 'Page & Container',
    'backdrop_color' => 'Cor do pano de fundo',
    'left_sidebar' => 'Barra lateral da esquerda',
    'right_sidebar' => 'Barra lateral da direita',
    'modal_sidebar' => 'Barra lateral do modal',
    'special_sidebar' => 'Barra lateral Especial',
    'backdrop_helper' => 'Isso é anulado pelo estilo da barra lateral!',
    'icon_alignment_helper' => 'Isso é anulado pelo estilo de barra lateral dobrada da barra lateral esquerda!',
    'letter_icon_helper' => 'Exibido apenas quando não há ícone definido para o item no menu!',
    'page' => 'Página',
    'page_header' => 'Cabeçalho da página',
    'light' => 'luz',
    'dark' => 'Escuro',
    'push' => 'Push',
    'position' => 'Posição',
    'notification_demo' => 'Esta é uma notificação de demonstração!',
    'boxed' => 'Boxed',
    'push_content' => 'Push content',
    'over' => 'Over',
    'folded' => 'Guardado',
    'off_canvas' => 'Fora da tela',
    'transparent' => 'Transparente',
    'notification' => 'Notificação',
    'right' => 'Direita',
    'left' => 'Esquerda',
    'enable' => 'Habilitar',
    'disable' => 'Desabilitar',
    'duration' => 'Duração',
    'seconds' => 'Segundos',
    'top_left' => 'Topo à esquerda',
    'top_center' => 'Topo ao centro',
    'top_right' => 'Topo à direita',
    'bottom_left' => 'Inferior esquerdo',
    'bottom_center' => 'Centro Inferior',
    'bottom_right' => 'Canto inferior direito',
  ),
  'ui_config' => 'UI Configuration',
);
