<?php return array (
    'misc' => 'Misc',
    'form_some_error' => 'Ocorreu um erro com o formulário, verifique e envie novamente.',
    'get_user_media_not_supported' => 'Alguns recursos não são suportados pelo seu navegador! Certifique-se de que está usando a versão mais recente dos navegadores suportados e que este site é seguro (HTTPS).',
    'error_unknown' => 'Algum erro desconhecido!',
    'solve_and_refresh' => 'Resolva o problema e atualize esta página!',
    'popup_blocker_alert' => 'O bloqueador de pop-ups está ativado! Por favor, adicione este site à sua lista de exceções.',
    'unsaved_confirm' => array(
        'title' => 'Você tem alterações não salvas!',
        'text' => 'Você realmente quer sair? Você não poderá reverter isso!',
        'confirm_btn' => 'Sim, sair!',
        'cancel_btn' => 'Não, ficar!',
    ),
    'action_confirm' => array(
        'title' => 'Você tem certeza?',
        'text' => 'Deseja realmente prosseguir com esta ação?',
        'confirm_btn' => 'Sim, prossiga!',
        'cancel_btn' => 'Não!',
    ),
    'refresh_confirm' => array(
        'title' => 'We are experiencing some issues!',
        'text' => 'Estamos enfrentando alguns problemas!',
        'confirm_btn' => 'Sim, atualize!',
        'cancel_btn' => 'Não!',
    ),
    'share_alert' => array(
        'text' => 'Clique em copiar e compartilhe com seus colegas.',
        'confirm_btn' => 'Coiar URL',
        'cancel_btn' => 'Cancelar',
    ),
    'media' => array(
        'permission_denied' => 'Você negou as permissões necessárias!',
        'permission_denied_text' => 'Este aplicativo precisa dessas permissões para funcionar!',
        'not_found' => 'Faltam alguns dispositivos necessários!',
        'not_found_text' => 'Este aplicativo precisa desses dispositivos para funcionar!',
        'unreadable' => 'Alguns dispositivos necessários ilegíveis!',
        'unreadable_text' => 'Este aplicativo precisa desses dispositivos em condições de funcionamento para funcionar!',
        'security' => 'Alguns dispositivos necessários ilegíveis!',
        'security_text' => 'Este aplicativo precisa desses dispositivos em boas condições para funcionar!',
        'missing' => 'Dispositivos ausentes!',
        'missing_text' => 'Os seguintes dispositivos / dispositivos necessários estão faltando: atributo',
    ),
);
