<?php
return array(
    'about' => 'Sobre',
    'product_support_subject' => 'Sujeito',
    'product_support_body' => 'Insira os detalhes',
    'product_download' => 'Download',
    'setup_title' => 'Configuração',
    'update_download' => 'Download & Atualização',
    'product' => 'Produto',
    'product_information' => 'informação do produto',
    'version' => 'Versão',
    'download' => 'Download',
    'update_download' => 'Download & Atualização',
    'no_internet_connection' => 'Sem conexão à Internet.',
    'install' => array(
        'admin_setup' => 'Configuração de administrador',
        'back_button_content' => 'Voltar',
        'could_not_establish_connection' => 'Parece que você forneceu detalhes incorretos do banco de dados. Verifique sua conexão de banco de dados novamente.',
        'contact_script_author' => 'Há algo errado. Entre em contato com o autor do script.',
        'table_exist_in_database' => 'Parece que seu banco de dados tem alguma tabela existente. A instalação requer um banco de dados vazio para prosseguir. Esvazie seu banco de dados.',
        'database_setup' => 'Configuração de banco de dados',
        'props' => array(
            'db_database' => 'Nome do banco de dados',
            'db_host' => 'Hostname',
            'db_password' => 'Senha do banco de dados',
            'db_port' => 'Porta de banco de dados',
            'db_username' => 'Nome de usuário do banco de dados',
            'first_name' => 'Primeiro nome',
            'last_name' => 'Último nome',
            'username' => 'Nome do usuário',
            'email' => 'Email',
            'name' => 'Nome',
            'password' => 'Senha',
            'password_confirmation' => 'Confirmar Senha',
            'contact_number' => 'Número de Contato',
        ),
        'completed' => 'Instalação completa. Agora você pode fazer o login.',
        'finish_button_content' => 'Finalizar',
        'fix_folder_error' => 'Há algum problema com a permissão da pasta. Por favor, corrija.',
        'fix_server_error' => 'O servidor não atende aos requisitos. Por favor, corrija.',
        'folder_permissions' => 'Permissões de pasta',
        'import_configuration_data' => 'Importar dados de configuração',
        'install' => 'Instalar',
        'install_wizard' => 'Assistente de instalação',
        'installation_processing' => 'Processamento de instalação. Isso pode levar algum tempo, por favor, não atualize ou envie o formulário novamente!',
        'next_button_content' => 'Próximo',
        'pre_requisite' => 'Pré Requisito',
        'ready_to_go' => 'Pronto para ir!',
        'ready_to_go_message' => 'Aqui está a etapa final. Basta verificar sua compra e você estará pronto para prosseguir. Se você tiver certeza de instalar o aplicativo com os detalhes fornecidos, clique no botão Concluir. Você ainda tem a chance de verificar novamente seus dados!',
        'server_requirements' => 'Requisitos do servidor',
        'sub_title' => 'Assistente de instalação com um clique',
        'url' => 'URL de instalação',
    ),
    'update' => array(
        'update' => 'Atualização',
        'product_update' => 'Atualiação de produto',
        'file_missing' => 'Nenhum arquivo de atualização encontrado.',
        'missing_zip_extension' => 'Extensão Zip não habilitada.',
        'not_available' => 'Nenhuma atualização disponível.',
        'downloaded' => 'Download atualizado.',
        'updated' => 'Produto atualizado.',
    ),
    'license' => array(
        'license' => 'Licença',
        'verification' => 'Verificação de Licença',
        'invalid_license' => 'Sua licença não é válida. Insira os detalhes da licença novamente.',
        'get_access_code' => 'Obtenha o código de acesso',
        'props' => array(
            'access_code' => 'Código de acesso',
            'envato_email' => 'Email da conta Envato',
        ),
        'tip_access_code' => 'Se você adquiriu o aplicativo com Envato, você pode obter o código de acesso clicando no botão abaixo e, em seguida, logando com sua conta Envato.',
        'verify' => 'Verificar',
        'verified' => 'Licença Verificada.',
    ),
    'support' => array(
        'support' => 'Suporte',
        'body' => 'Corpo',
        'subject' => 'Sujeito',
        'request_submitted' => 'Sua solicitação de suporte foi enviada.',
    ),
);
