<?php
return array(
    'user' => 'Usuário',
    'users' => 'Usuários',
    'props' => array(
        'email' => 'Email',
        'username' => 'Nome de usuário',
        'name' => 'Nome',
        'password' => 'Senha',
        'password_confirmation' => 'Confirmar Senha',
        'address_line_1' => 'Linha de endereço 1',
        'address_line_2' => 'Linha de endereço 2',
        'avatar' => 'Avatar',
        'phone' => 'Telefone',
        'city' => 'Cidade',
        'contact' => 'Contacto',
        'contact_number' => 'Número de contao',
        'anniversary_date' => 'Data de Aniversário',
        'birth_date' => 'Date de Nascimento',
        'gender' => 'Gênero',
        'social' => 'Social', 'social_profile' => 'Rede Social',
        'state' => 'Estado',
        'status' => 'Status',
        'work_email' => 'Email Profissional',
        'work_phone' => 'Telefone do Trabalho',
        'work_phone_extension' => 'Extensão do Telefone do Trabalho',
        'zipcode' => 'CEP',
        'image' => 'Image',
    ),
    'profile' => 'Perfil',
    'your_profile' => 'Seu Perfil',
    'change_password' => 'Mudar Senha',
    'user_detail' => 'Detalhes do usuário',
    'force_password' => 'Forçar mudança de senha',
    'user_preference' => 'Preferência do usuário',
    'user_action_activate' => 'Ativar',
    'user_action_approve' => 'Aprovar',
    'user_action_ban' => 'Ban',
    'user_action_disapprove' => 'Desaprovar',
    'status_activated' => 'Ativado',
    'status_banned' => 'Banido',
    'status_disapproved' => 'Reprovado',
    'status_pending_activation' => 'Ativação Pendente',
    'status_pending_approval' => 'Aprovação pendente',
    'send_welcome_email' => 'Enviar e-mail de boas-vindas',
    'avatar_removed' => 'Avatar removed',
    'avatar_uploaded' => 'Avatar removido',
    'permission_denied' => 'Você não está autorizado a realizar esta ação.',
    'module_description' => 'Adicionar novo usuário com funções diferentes, atualizar perfil, avatar.',
);
