<?php return array (
  'accepted' => 'O :atributo deve ser aceito.',
  'active_url' => 'O :attribute não é um URL válido.',
  'after' => 'O :atributo deve ser uma data após :data.',
  'after_or_equal' => 'O :attribute deve ser uma data posterior ou igual a :data.',
  'alpha' => 'O: attribute só pode conter letras.',
  'alpha_dash' => 'O :attribute só pode conter letras, números e sublinhados.',
  'alpha_num' => 'O :atributo pode conter apenas letras e números.',
  'array' => 'O :atributo deve ser uma matriz.',
  'attributes' => 
  array (
  ),
  'before' => 'O :atributo deve ser uma data antes de :data.',
  'before_or_equal' => 'O :atributo deve ser uma data anterior ou igual a :data.',
  'between' => 
  array (
    'numeric' => 'O :atributo deve estar entre :min and :max.',
    'file' => 'O :atributo deve estar entre :min and :max kilobytes.',
    'string' => 'O :atributo deve estar entre :min e :max caracteres.',
    'array' => 'O :attribute must have between :min e :max items.',
  ),
  'boolean' => 'O :campo de atributo deve ser verdadeiro ou falso.',
  'confirmed' => 'O :a confirmação do atributo não corresponde.',
  'custom' => 
  array (
    'attribute-name' => 
    array (
      'rule-name' => 'mensagem personalizada',
    ),
  ),
  'date' => 'O :atributo não é uma data válida.',
  'date_equals' => 'O :atributo deve ser uma data igual a :date.',
  'date_format' => 'O :atributo não corresponde ao formato :formato.',
  'different' => 'O :atributo e :outro deve ser diferente.',
  'digits' => 'O :atributo deve ser :dígitos dígitos.',
  'digits_between' => 'O :atributo deve estar entre :min e :max dígitos.',
  'dimensions' => 'O :atributo tem dimensões de imagem inválidas.',
  'distinct' => 'O :campo de atributo tem um valor duplicado.',
  'email' => 'O :atributo deve ser um endereço de e-mail válido.',
  'ends_with' => 'O :atributo deve terminar com um dos seguintes: :valores.',
  'exists' => 'O atributo selecionado: é inválido.',
  'file' => 'O :atributo deve ser um arquivo.',
  'filled' => 'O :atributo deve conter um valor.',
  'gt' => 
  array (
    'numeric' => 'O :atributo deve ser maior que :valor.',
    'file' => 'O :atributo deve ser maior que :valor kilobytes.',
    'string' => 'O :atributo deve ser maior que :valor characters.',
    'array' => 'The :attribute must have more than :valor items.',
  ),
  'gte' => 
  array (
    'numeric' => 'O :atributo deve ser maior ou igual a :valor.',
    'file' => 'O :atributo deve ser maior ou igual a :valor kilobytes.',
    'string' => 'O :deve ser maior ou igual a :valor characteres.',
    'array' => 'O :atributo deve ter :valor items ou mais.',
  ),
  'image' => 'O :atributo deve ser uma imagem.',
  'in' => 'O :atributo selecionado é invalido.',
  'in_array' => 'O campo :atributo não existe en :outro.',
  'integer' => 'O :atributo deve ser um inteiro.',
  'ip' => 'O :atributo deve ser um endereço válido de IP.',
  'ipv4' => 'O :atributo deve ser um endereço IPv4 válido.',
  'ipv6' => 'O :atributo deve ser um endereço IPv6 válido.',
  'json' => 'O :atribute deve ser um endereço IPv6 válido.',
  'lt' => 
  array (
    'numeric' => 'O :atributo deve ser menor que :valor.',
    'file' => 'O :atributo deve ser menor que :valor kilobytes.',
    'string' => 'O :atributo deve ser menor que :valor caracteres.',
    'array' => 'O :atributo deve ser menor que :valor items.',
  ),
  'lte' => 
  array (
    'numeric' => 'O :atributo deve ser menor ou igual :valor.',
    'file' => 'O :atributo deve ser menor ou igual :valor kilobytes.',
    'string' => 'O :atributo deve ser menor ou igual :valor caracteres.',
    'array' => 'The :atributo deve ser menor ou igual :valor items.',
  ),
  'max' => 
  array (
    'numeric' => 'O :atributo não pode ser maior que :max.',
    'file' => 'O :atributo não pode ser maior que :max kilobytes.',
    'string' => 'O :atributo não pode ser maior que :max characters.',
    'array' => 'O :atributo não pode ser maior que :max items.',
  ),
  'mimes' => 'O :atributo deve ser um arquivo do tipo: :valores.',
  'mimetypes' => 'O :atributo deve ser um arquivo do tipo: :valores.',
  'min' => 
  array (
    'numeric' => 'O :atributo deve ter pelo menos :min.',
    'file' => 'O :atributo deve ter pelo menos :min kilobytes.',
    'string' => 'O :atributo deve ter pelo menos :min characters.',
    'array' => 'O :atributo deve ter pelo menos :min items.',
  ),
  'not_in' => 'O :atributo selecionado é inválido.',
  'not_regex' => 'O formato do :atributo é inválido.',
  'numeric' => 'The :attribute must be a number.',
  'password' => 'A senha está incorreta',
  'present' => 'O campo de :atributo deve estar presente',
  'regex' => 'O formato do :atributo é inválido',
  'required' => 'O campo :atributo é obrigatório.',
  'required_if' => 'O campo :atributo é obrigatório quando :outro é :valor.',
  'required_unless' => 'O campo de :atributo é obrigatório, a menos que outro esteja em :valores.',
  'required_with' => 'O campo :atributo é obrigatório quando :valores estiver presente.',
  'required_with_all' => 'O campo :atributo é obrigatório quando :valores estão presentes.',
  'required_without' => 'O campo :atributo é obrigatório quando :valores não estiver presente. ',
  'required_without_all' => 'O campo :atributo é obrigatório quando nenhum dos :valores está presente.',
  'same' => 'O :atributo e :outro devem corresponder.',
  'size' => 
  array (
    'numeric' => 'O :atributo deve ser :size.',
    'file' => 'O :atributo deve ter :tamanho kilobytes.',
    'string' => 'O :atributo deve ter :tamanho characters.',
    'array' => 'O :atributo deve conter :tamanho :items.',
  ),
  'starts_with' => 'O :attribute deve começar com um dos seguintes: :valores.',
  'string' => 'O :atributo deve ser uma string.',
  'timezone' => 'O :atributo deve ser uma zona válida.',
  'unique' => 'O :atributo já foi usado.',
  'uploaded' => 'O :atributo falhou ao carregar.',
  'url' => 'O formato :atributo é inválido.',
  'uuid' => 'O :atributo deve ser um UUID válido.',
  'validation' => 'Validação',
);
